import { Product, ProductCategory, DeviceCondition, ImeiPair, ShopSettings } from '../types';
import { 
  extractNormalizedRam, 
  extractNormalizedRom, 
  extractNormalizedColor, 
  generateVariantSku 
} from './variantUtils';

export interface ParsedCsvProductRow {
  rowNumber: number;
  rawText: string;
  isValid: boolean;
  errors: string[];
  warnings: string[];
  product: Product;
  parsedImeis: ImeiPair[];
  isExistingVariantMatch?: boolean;
}

export interface CsvTemplatePreset {
  id: string;
  name: string;
  description: string;
  csvContent: string;
}

/**
 * Robust CSV/TSV tokenizer that handles double quotes, escaped quotes, and multiple delimiters
 */
export function tokenizeCsvLine(line: string, delimiter: string = ','): string[] {
  const result: string[] = [];
  let current = '';
  let inQuotes = false;
  
  for (let i = 0; i < line.length; i++) {
    const char = line[i];
    const nextChar = line[i + 1];

    if (char === '"') {
      if (inQuotes && nextChar === '"') {
        // Escaped double quote inside quotes
        current += '"';
        i++;
      } else {
        // Toggle quote state
        inQuotes = !inQuotes;
      }
    } else if (char === delimiter && !inQuotes) {
      result.push(cleanToken(current));
      current = '';
    } else {
      current += char;
    }
  }
  
  result.push(cleanToken(current));
  return result;
}

/**
 * Trims and strips any enclosing quotes from a token
 */
export function cleanToken(token: string): string {
  let s = token.trim();
  if ((s.startsWith('"') && s.endsWith('"')) || (s.startsWith("'") && s.endsWith("'"))) {
    s = s.slice(1, -1).trim();
  }
  return s;
}

/**
 * Expands scientific notation (e.g. 8.63E+14 or 1.11E+11) frequently generated by Excel
 * for large numbers such as Barcodes and IMEIs into full integer digit strings.
 */
export function expandScientificNotation(val: string): string {
  if (!val) return '';
  const trimmed = val.trim();
  // Matches e.g. 8.62675065232361E+14, 1.11E+11, 3.6e+14
  if (/^[+-]?\d+(?:\.\d+)?[eE][+-]?\d+$/.test(trimmed)) {
    try {
      const num = Number(trimmed);
      if (!isNaN(num) && isFinite(num)) {
        return BigInt(Math.round(num)).toString();
      }
    } catch {
      return trimmed;
    }
  }
  return trimmed;
}

/**
 * Detects the most probable delimiter for tabular text (comma, tab, semicolon, pipe)
 */
export function detectDelimiter(text: string): string {
  const firstLines = text.split(/\r?\n/).filter(l => l.trim().length > 0).slice(0, 5);
  if (firstLines.length === 0) return ',';

  const counts: Record<string, number> = { '\t': 0, ',': 0, ';': 0, '|': 0 };

  firstLines.forEach(line => {
    let inQuotes = false;
    for (let i = 0; i < line.length; i++) {
      const char = line[i];
      if (char === '"') {
        inQuotes = !inQuotes;
      } else if (!inQuotes && counts[char] !== undefined) {
        counts[char]++;
      }
    }
  });

  let bestDelimiter = ',';
  let maxCount = -1;

  // Prefer tabs for TSV (Excel/Google Sheets copy paste) if prevalent
  for (const [del, count] of Object.entries(counts)) {
    if (count > maxCount && count > 0) {
      maxCount = count;
      bestDelimiter = del;
    }
  }

  return bestDelimiter;
}

/**
 * Normalizes category string to valid ProductCategory enum value
 */
export function normalizeCategory(input?: string, contextName?: string): ProductCategory {
  if (!input || input === '-' || input.toLowerCase() === 'none') {
    if (contextName) {
      const lower = contextName.toLowerCase();
      if (lower.includes('cook') || lower.includes('pot') || lower.includes('pan') || lower.includes('kettle') || lower.includes('blender') || lower.includes('fryer') || lower.includes('wok') || lower.includes('rice cooker') || lower.includes('ဟင်းချက်အိုး')) {
        return 'cookware';
      }
      if (lower.includes('case') || lower.includes('cover') || lower.includes('charger') || lower.includes('cable') || lower.includes('power bank') || lower.includes('watch') || lower.includes('earbuds') || lower.includes('audio') || lower.includes('fan')) {
        return 'accessories_gadgets';
      }
      if (lower.includes('sim') || lower.includes('esim') || lower.includes('topup') || lower.includes('top-up')) {
        return 'sim_cards';
      }
      if (lower.includes('used') || lower.includes('secondhand') || lower.includes('preowned')) {
        return 'pre_owned_phones';
      }
    }
    return 'brand_new_phones';
  }

  const clean = input.toLowerCase().trim();

  // Direct matches to labels & enums
  if (clean === 'brand_new_phones' || clean === 'new_phones' || clean.includes('brand new phone') || clean === 'smartphones') {
    return 'brand_new_phones';
  }
  if (clean === 'pre_owned_phones' || clean === 'used_phones' || clean.includes('pre-owned') || clean.includes('preowned') || clean.includes('used phone') || clean.includes('secondhand')) {
    return 'pre_owned_phones';
  }
  if (clean === 'accessories_gadgets' || clean === 'accessories' || clean === 'gadgets' || clean.includes('accessori') || clean.includes('gadget') || clean.includes('charger') || clean.includes('cable')) {
    return 'accessories_gadgets';
  }
  if (clean === 'cookware' || clean.includes('cook') || clean.includes('kitchen') || clean.includes('ဟင်းချက်အိုး')) {
    return 'cookware';
  }
  if (clean === 'sim_cards' || clean === 'sim_topup' || clean.includes('sim')) {
    return 'sim_cards';
  }
  if (clean === 'spare_parts' || clean.includes('spare') || clean.includes('part') || clean.includes('screen') || clean.includes('lcd')) {
    return 'spare_parts';
  }

  const noSpecial = clean.replace(/[^a-z0-9]/g, '');
  if (noSpecial.includes('cook')) return 'cookware';
  if (noSpecial.includes('access') || noSpecial.includes('gadget')) return 'accessories_gadgets';
  if (noSpecial.includes('used') || noSpecial.includes('second')) return 'pre_owned_phones';
  if (noSpecial.includes('phone') || noSpecial.includes('mobile')) return 'brand_new_phones';

  return 'brand_new_phones';
}

/**
 * Normalizes condition string to DeviceCondition enum value
 */
export function normalizeCondition(input?: string): DeviceCondition {
  if (!input || input === '-' || input.toLowerCase() === 'none') return 'brand_new';
  const clean = input.toLowerCase().replace(/[^a-z0-9+]/g, '');

  if (clean.includes('aplus') || clean.includes('a+') || clean.includes('gradeaplus') || clean.includes('likenew') || clean.includes('99')) {
    return 'used_grade_a_plus';
  }
  if (clean.includes('gradea') || clean.includes('useda') || clean.includes('excellent') || clean.includes('95')) {
    return 'used_grade_a';
  }
  if (clean.includes('gradeb') || clean.includes('usedb') || clean.includes('good') || clean.includes('90')) {
    return 'used_grade_b';
  }
  if (clean.includes('gradec') || clean.includes('usedc') || clean.includes('fair') || clean.includes('85')) {
    return 'used_grade_c';
  }
  if (clean.includes('used') || clean.includes('second') || clean.includes('preowned')) {
    return 'used_grade_a';
  }

  return 'brand_new';
}

/**
 * Cleans currency/number strings (e.g. "3,500,000 Ks" -> 3500000, "11.3%" -> 11.3)
 */
export function parseCleanNumber(val?: string | number, fallback: number = 0): number {
  if (val === undefined || val === null) return fallback;
  if (typeof val === 'number') return isNaN(val) ? fallback : val;
  
  const str = String(val).trim();
  if (str === '-' || str === 'none' || str === 'n/a') return fallback;

  // Handle scientific notation numbers like 1.5E+11
  const expanded = expandScientificNotation(str);
  const cleaned = expanded.replace(/[^0-9.-]/g, '');
  const num = parseFloat(cleaned);
  return isNaN(num) ? fallback : num;
}

/**
 * Brand detection from name if brand column omitted
 */
export function detectBrandFromName(name: string): string {
  const lower = name.toLowerCase();
  const KNOWN_BRANDS = [
    'Apple', 'Samsung', 'Xiaomi', 'Redmi', 'POCO', 'Google', 'OPPO', 
    'Vivo', 'Realme', 'OnePlus', 'Honor', 'Huawei', 'Sony', 'Motorola',
    'Asus', 'Infinix', 'Tecno', 'Nothing', 'Anker', 'Baseus', 'Remax',
    'Hoco', 'Joyroom', 'Ugreen', 'JBL', 'Marshall', 'Sony', 'Haylou', 'Mibro',
    'Daw Pu', 'Ansty', 'FastCharge', 'Gthick', 'Olochi', 'Children SV'
  ];

  for (const b of KNOWN_BRANDS) {
    if (lower.startsWith(b.toLowerCase() + ' ') || lower.startsWith(b.toLowerCase() + '-') || lower.includes(` ${b.toLowerCase()} `)) {
      return b;
    }
  }

  if (lower.startsWith('iphone') || lower.startsWith('ipad') || lower.startsWith('airpods') || lower.startsWith('macbook')) {
    return 'Apple';
  }
  if (lower.startsWith('galaxy')) {
    return 'Samsung';
  }
  if (lower.startsWith('redmi') || lower.startsWith('poco')) {
    return 'Xiaomi';
  }

  return '';
}

/**
 * Parses combined specs string (such as "4GB RAM • 64GB • Black" or "8GB RAM • 128GB • Blue")
 * into separated RAM, ROM, and Color attributes.
 */
export function parseSpecsString(specs?: string): { ram?: string; rom?: string; color?: string } {
  if (!specs || !specs.trim()) return {};
  const trimmed = specs.trim();
  if (trimmed === '-' || trimmed.toLowerCase() === 'none' || trimmed.toLowerCase() === 'n/a' || trimmed.toLowerCase() === 'standard') {
    return {};
  }

  let ram: string | undefined;
  let rom: string | undefined;
  let color: string | undefined;

  // Split by bullet •, pipe |, or slash /
  const parts = trimmed.split(/[•|/]+/).map(p => p.trim()).filter(Boolean);

  // First pass: find RAM (e.g. "4GB RAM" or "4GB")
  parts.forEach(p => {
    const ramMatch = p.match(/(\d+\s*GB)\s*RAM/i) || p.match(/\b(\d+)\s*GB\s*RAM\b/i);
    if (ramMatch && !ram) {
      ram = ramMatch[1].replace(/\s+/g, '').toUpperCase();
    }
  });

  // Second pass: find ROM (look for GB or TB not identified as RAM)
  parts.forEach(p => {
    const romMatch = p.match(/\b(\d+\s*(?:GB|TB))\b/i);
    if (romMatch && !rom) {
      const candidate = romMatch[1].replace(/\s+/g, '').toUpperCase();
      if (p.toLowerCase().includes('ram')) {
        if (!ram) ram = candidate;
      } else {
        rom = candidate;
      }
    }
  });

  // Third pass: find Color (parts that are not pure RAM or ROM numbers)
  parts.forEach(p => {
    const isRamPart = /ram/i.test(p) || /^\d+\s*GB\s*RAM$/i.test(p);
    const isRomPart = /^\d+\s*(?:GB|TB)$/i.test(p.trim());
    if (!isRamPart && !isRomPart && p !== '-' && !color) {
      color = p;
    }
  });

  // Fallback regex on entire string if parts did not catch
  if (!ram) {
    const fullRamMatch = trimmed.match(/(\d+\s*GB)\s*RAM/i);
    if (fullRamMatch) ram = fullRamMatch[1].replace(/\s+/g, '').toUpperCase();
  }
  if (!rom) {
    const withoutRam = trimmed.replace(/\d+\s*GB\s*RAM/i, '');
    const fullRomMatch = withoutRam.match(/(\d+\s*(?:GB|TB))/i);
    if (fullRomMatch) rom = fullRomMatch[1].replace(/\s+/g, '').toUpperCase();
  }

  return { ram, rom, color };
}

/**
 * Parses IMEI string into structured ImeiPair array.
 * Supports delimiters: commas, semicolons, slashes, pipes, spaces.
 * Also expands any scientific notation numbers from Excel (e.g. 8.63E+14).
 */
export function parseImeiListString(rawImeis?: string): ImeiPair[] {
  if (!rawImeis || !rawImeis.trim()) return [];
  const clean = rawImeis.trim();
  if (clean === '-' || clean === '0' || clean.toLowerCase() === 'none' || clean.toLowerCase() === 'n/a') {
    return [];
  }

  const pairs: ImeiPair[] = [];
  // Split multiple units by semicolons, newlines, or double spaces
  const units = clean
    .split(/[;\n]+/)
    .map(u => u.trim())
    .filter(Boolean);

  units.forEach(unit => {
    // Check if unit has dual IMEI separated by / or |
    if (unit.includes('/') || unit.includes('|')) {
      const parts = unit.split(/[/|]+/).map(p => {
        const expanded = expandScientificNotation(p.trim());
        return expanded.replace(/[^0-9]/g, '');
      }).filter(Boolean);

      if (parts[0]) {
        pairs.push({
          imei1: parts[0],
          imei2: parts[1] || undefined,
          status: 'In Stock'
        });
      }
    } else {
      const expanded = expandScientificNotation(unit);
      const digitsOnly = expanded.replace(/[^0-9]/g, '');

      // Single standard IMEI (14-16 digits)
      if (digitsOnly.length >= 14 && digitsOnly.length <= 16) {
        pairs.push({
          imei1: digitsOnly,
          status: 'In Stock'
        });
      } else if (digitsOnly.length >= 28 && digitsOnly.length <= 32) {
        // Dual IMEI concatenated (15 + 15 digits)
        pairs.push({
          imei1: digitsOnly.slice(0, 15),
          imei2: digitsOnly.slice(15, 30),
          status: 'In Stock'
        });
      } else {
        // Try splitting by comma
        const subItems = unit.split(',').map(s => {
          const exp = expandScientificNotation(s.trim());
          return exp.replace(/[^0-9]/g, '');
        }).filter(s => s.length >= 14 && s.length <= 16);

        if (subItems.length > 0) {
          subItems.forEach(im => {
            pairs.push({ imei1: im, status: 'In Stock' });
          });
        } else if (digitsOnly.length >= 8) {
          // Serial number or short barcode/serial
          pairs.push({ imei1: digitsOnly, status: 'In Stock' });
        }
      }
    }
  });

  return pairs;
}

/**
 * Maps raw header text to normalized field key using flexible matching.
 * Seamlessly handles:
 * - "Cost Price (Ks)", "Selling Price (Ks)", "Stock (Units)", "Min Alert Level"
 * - "Serialized IMEIs", "Specs / Storage / Color", "Product Name", "SKU", "Barcode"
 * - Standard template columns: Name, Brand, Category, Condition, CostPrice, SellingPrice, etc.
 */
export function matchHeaderKey(rawHeader: string): string | null {
  const norm = rawHeader.toLowerCase().replace(/[^a-z0-9]/g, '');
  const origLower = rawHeader.toLowerCase().trim();

  // 1. Cost Price: matches "cost price (ks)", "costprice", "cost", "unit cost", "buy price", "purchase cost"
  if (
    norm.includes('cost') || 
    norm.includes('buyprice') || 
    norm.includes('buyingprice') || 
    norm.includes('purchaseprice') || 
    norm.includes('purchasecost') ||
    origLower.includes('cost price') ||
    origLower.includes('purchase price')
  ) {
    return 'costPrice';
  }

  // 2. Selling Price: matches "selling price (ks)", "sellingprice", "sellprice", "retail price", "sale price", "price"
  // Note: must NOT match margin or profit
  if (
    !norm.includes('cost') && 
    !norm.includes('profit') && 
    !norm.includes('margin') &&
    (
      norm.includes('selling') || 
      norm.includes('sellprice') || 
      norm.includes('retail') || 
      norm.includes('saleprice') ||
      norm === 'price' || 
      norm.startsWith('price') ||
      origLower.includes('selling price') ||
      origLower.includes('retail price')
    )
  ) {
    return 'sellingPrice';
  }

  // 3. Stock: matches "stock (units)", "stock", "qty", "quantity", "units", "count"
  // Note: must NOT match "min alert", "min stock", "stock status"
  if (
    !norm.includes('min') && 
    !norm.includes('alert') && 
    !norm.includes('status') &&
    (
      norm.startsWith('stock') || 
      norm === 'stock' || 
      norm === 'qty' || 
      norm === 'quantity' || 
      norm === 'units' || 
      norm === 'count' || 
      norm === 'inventory' ||
      origLower.includes('stock (units)')
    )
  ) {
    return 'stock';
  }

  // 4. Min Alert / Min Stock Alert: matches "min alert level", "min stock alert", "min alert", "reorder level"
  if (
    norm.includes('alert') || 
    norm.includes('reorder') || 
    (norm.includes('min') && norm.includes('stock')) ||
    origLower.includes('min alert') ||
    origLower.includes('alert level')
  ) {
    return 'minStockAlert';
  }

  // 5. IMEIs / Serial Numbers: matches "serialized imeis", "imeis", "imei", "serial numbers", "imei list"
  // Note: must NOT match "imei count"
  if (
    !norm.includes('count') && 
    !norm.includes('total') && 
    (
      norm.includes('imei') || 
      norm.includes('serial') ||
      origLower.includes('serialized imeis') ||
      origLower.includes('imei')
    )
  ) {
    return 'imeis';
  }

  // 6. Specs / Storage / Color (combined export column)
  if (
    norm.includes('specs') || 
    norm.includes('specification') ||
    origLower.includes('specs / storage / color') ||
    origLower.includes('specs')
  ) {
    return 'specs';
  }

  // 7. RAM: matches "ram", "ram size", "memory"
  if (
    !norm.includes('specs') &&
    (norm === 'ram' || norm === 'memory' || norm.startsWith('ram') || origLower === 'ram')
  ) {
    return 'ram';
  }

  // 8. ROM: matches "rom", "storage", "internal storage", "capacity"
  if (
    !norm.includes('specs') &&
    (norm === 'rom' || norm === 'storage' || norm.startsWith('rom') || norm === 'capacity' || norm === 'internalstorage')
  ) {
    return 'rom';
  }

  // 9. Color: matches "color", "colour", "finish"
  if (
    !norm.includes('specs') &&
    (norm.includes('color') || norm.includes('colour') || norm.includes('finish'))
  ) {
    return 'color';
  }

  // 10. SKU: matches "sku", "product sku", "item code", "product code"
  if (
    norm === 'sku' || norm.includes('sku') || norm === 'itemcode' || norm === 'productcode'
  ) {
    return 'sku';
  }

  // 11. Barcode: matches "barcode", "upc", "ean"
  if (
    norm.includes('barcode') || norm === 'upc' || norm === 'ean'
  ) {
    return 'barcode';
  }

  // 12. Subcategory: matches "subcategory", "sub category", "subcat"
  if (
    norm.includes('subcat') || norm.includes('subcategory') || norm.includes('segment')
  ) {
    return 'subCategory';
  }

  // 13. Category: matches "category", "cat", "product category" (not subcategory)
  if (
    !norm.includes('sub') &&
    (norm === 'category' || norm === 'cat' || norm === 'type' || norm.includes('category'))
  ) {
    return 'category';
  }

  // 14. Condition: matches "condition", "grade", "state", "quality"
  if (
    norm.includes('condition') || norm.includes('grade') || norm.includes('state')
  ) {
    return 'condition';
  }

  // 15. Warranty: matches "warranty", "warranty months", "warranty period"
  if (
    norm.includes('warranty')
  ) {
    return 'warranty';
  }

  // 16. Description: matches "description", "notes", "details", "memo"
  if (
    norm.includes('description') || norm === 'notes' || norm === 'details' || norm === 'memo'
  ) {
    return 'description';
  }

  // 17. Brand: matches "brand", "make", "manufacturer"
  if (
    norm === 'brand' || norm === 'brandname' || norm === 'make' || norm === 'manufacturer'
  ) {
    return 'brand';
  }

  // 18. Product Name: matches "product name", "name", "title", "model name", "product", "item"
  if (
    !norm.includes('brand') && !norm.includes('color') &&
    (
      norm === 'name' || 
      norm === 'productname' || 
      norm === 'itemname' || 
      norm === 'title' || 
      norm === 'model' || 
      norm === 'modelname' ||
      norm === 'product' ||
      norm === 'item' ||
      origLower.includes('product name')
    )
  ) {
    return 'name';
  }

  return null;
}

/**
 * Main parser function to convert raw CSV / TSV text to structured Product records
 */
export function parseBulkCsvProducts(
  rawText: string,
  existingProducts: Product[] = [],
  settings?: ShopSettings
): {
  rows: ParsedCsvProductRow[];
  totalValid: number;
  totalErrors: number;
  totalUnits: number;
  totalValuationCost: number;
  totalValuationSelling: number;
  delimiter: string;
} {
  const trimmed = rawText.trim();
  if (!trimmed) {
    return {
      rows: [],
      totalValid: 0,
      totalErrors: 0,
      totalUnits: 0,
      totalValuationCost: 0,
      totalValuationSelling: 0,
      delimiter: ','
    };
  }

  const delimiter = detectDelimiter(trimmed);
  const rawLines = trimmed.split(/\r?\n/).filter(line => line.trim().length > 0);

  if (rawLines.length === 0) {
    return {
      rows: [],
      totalValid: 0,
      totalErrors: 0,
      totalUnits: 0,
      totalValuationCost: 0,
      totalValuationSelling: 0,
      delimiter
    };
  }

  // Header detection
  const firstRowRawTokens = tokenizeCsvLine(rawLines[0], delimiter);
  const matchedKeys = firstRowRawTokens.map(tok => matchHeaderKey(tok));
  
  // A header row is confirmed if we recognized at least 2 distinct known keys,
  // or a key like name/product/price/cost/sku/stock
  const hasHeaderRow = matchedKeys.some(k => 
    k === 'name' || k === 'costPrice' || k === 'sellingPrice' || k === 'stock' || k === 'sku' || k === 'brand'
  );

  // Column index mappings
  const colMap: Record<string, number> = {
    name: -1,
    brand: -1,
    category: -1,
    subCategory: -1,
    condition: -1,
    costPrice: -1,
    sellingPrice: -1,
    stock: -1,
    minStockAlert: -1,
    specs: -1,
    ram: -1,
    rom: -1,
    color: -1,
    sku: -1,
    barcode: -1,
    imeis: -1,
    warranty: -1,
    description: -1,
  };

  let dataLines: string[] = [];

  if (hasHeaderRow) {
    firstRowRawTokens.forEach((rawHeader, idx) => {
      const key = matchHeaderKey(rawHeader);
      if (key && colMap[key] === -1) {
        colMap[key] = idx;
      }
    });

    dataLines = rawLines.slice(1);
  } else {
    // Default standard positional column mapping
    // Name, Brand, Category, SubCategory, Condition, CostPrice, SellingPrice, Stock, RAM, ROM, Color, SKU, Barcode, IMEIs, Warranty, Description
    colMap.name = 0;
    colMap.brand = 1;
    colMap.category = 2;
    colMap.subCategory = 3;
    colMap.condition = 4;
    colMap.costPrice = 5;
    colMap.sellingPrice = 6;
    colMap.stock = 7;
    colMap.ram = 8;
    colMap.rom = 9;
    colMap.color = 10;
    colMap.sku = 11;
    colMap.barcode = 12;
    colMap.imeis = 13;
    colMap.warranty = 14;
    colMap.description = 15;

    dataLines = rawLines;
  }

  const parsedRows: ParsedCsvProductRow[] = [];
  let totalValid = 0;
  let totalErrors = 0;
  let totalUnits = 0;
  let totalValuationCost = 0;
  let totalValuationSelling = 0;

  dataLines.forEach((line, lineIndex) => {
    const rowNumber = hasHeaderRow ? lineIndex + 2 : lineIndex + 1;
    const tokens = tokenizeCsvLine(line, delimiter);

    // Skip completely empty lines
    if (tokens.length === 0 || tokens.every(t => !t.trim())) {
      return;
    }

    const errors: string[] = [];
    const warnings: string[] = [];

    const getVal = (key: string): string => {
      const idx = colMap[key];
      return idx >= 0 && idx < tokens.length ? tokens[idx].trim() : '';
    };

    const rawName = getVal('name') || (colMap.name === -1 && tokens.length > 0 ? tokens[0].trim() : '');
    if (!rawName) {
      errors.push('Product name is required');
    }

    let brand = getVal('brand');
    if ((!brand || brand === '-') && rawName) {
      const autoBrand = detectBrandFromName(rawName);
      if (autoBrand) {
        brand = autoBrand;
      } else {
        warnings.push('Brand was not specified');
      }
    }

    const rawCategory = getVal('category');
    const category = normalizeCategory(rawCategory, rawName);
    const isPhone = category === 'brand_new_phones' || category === 'pre_owned_phones' || category === 'new_phones' || category === 'used_phones';

    const rawCondition = getVal('condition');
    const condition = isPhone && (category === 'pre_owned_phones' || category === 'used_phones') && !rawCondition
      ? 'used_grade_a'
      : normalizeCondition(rawCondition);

    let subCategory = getVal('subCategory') || undefined;
    if (subCategory === '-' || subCategory?.toLowerCase() === 'none') {
      subCategory = undefined;
    }

    // Combined specs parsing (e.g. from "Specs / Storage / Color" column in inventory export)
    const rawSpecs = getVal('specs');
    const specsParsed = parseSpecsString(rawSpecs);

    // RAM & ROM extraction (Dedicated column takes precedence, then combined specs, then Name)
    let ram = extractNormalizedRam(getVal('ram')) || specsParsed.ram;
    let rom = extractNormalizedRom(getVal('rom')) || specsParsed.rom;

    if (isPhone && !ram) {
      const nameRam = extractNormalizedRam('', rawName);
      if (nameRam) ram = nameRam;
    }
    if (isPhone && !rom) {
      const nameRom = extractNormalizedRom('', rawName);
      if (nameRom) rom = nameRom;
    }

    const color = extractNormalizedColor(getVal('color')) || specsParsed.color || (isPhone ? 'Standard' : undefined);

    const rawCost = getVal('costPrice');
    const costPrice = parseCleanNumber(rawCost, 0);

    const rawSelling = getVal('sellingPrice');
    const sellingPrice = parseCleanNumber(rawSelling, 0);

    if (sellingPrice <= 0) {
      errors.push('Selling price must be greater than 0');
    }
    if (costPrice > sellingPrice && sellingPrice > 0) {
      warnings.push(`Cost price (${costPrice.toLocaleString()}) is higher than selling price (${sellingPrice.toLocaleString()})`);
    }

    // Parse IMEIs
    const rawImeis = getVal('imeis');
    const parsedImeis = isPhone ? parseImeiListString(rawImeis) : [];

    // Calculate Stock
    const rawStock = getVal('stock');
    let stock = parseCleanNumber(rawStock, isPhone && parsedImeis.length > 0 ? parsedImeis.length : 1);
    if (isPhone && parsedImeis.length > 0) {
      // If IMEIs provided, stock must match at least the count of serialized IMEIs
      stock = Math.max(stock, parsedImeis.length);
    }
    if (stock < 0) {
      stock = 0;
    }

    const minStockAlert = parseCleanNumber(getVal('minStockAlert'), 0);
    const warrantyMonths = parseCleanNumber(getVal('warranty'), isPhone ? (category === 'new_phones' || category === 'brand_new_phones' ? 12 : 1) : 6);
    const description = getVal('description') || undefined;

    // SKU & Barcode preservation / fallback
    let sku = getVal('sku');
    if (!sku || sku === '-') {
      sku = generateVariantSku(brand || 'ITEM', rawName, ram, rom, color);
    }

    let barcode = getVal('barcode');
    if (!barcode || barcode === '-') {
      barcode = `${Math.floor(100000000000 + Math.random() * 900000000000)}`;
    } else {
      barcode = expandScientificNotation(barcode);
    }

    const storageStr = isPhone
      ? (ram && ram !== '-' ? `${ram} / ${rom || 'Standard'}` : (rom || undefined))
      : undefined;

    const flattenedImeiList = parsedImeis.map(p => p.imei1).concat(parsedImeis.filter(p => p.imei2).map(p => p.imei2!));

    // Construct Product Object
    const product: Product = {
      id: `prod-bulk-${Date.now()}-${lineIndex}-${Math.random().toString(36).substr(2, 4)}`,
      name: rawName,
      brand: brand || 'Generic',
      model: rawName,
      category,
      subCategory,
      condition,
      sku,
      barcode,
      costPrice,
      sellingPrice,
      stock,
      minStockAlert,
      ram: isPhone ? (ram || '-') : undefined,
      rom: isPhone ? (rom || '128GB') : undefined,
      storage: storageStr,
      color: isPhone ? (color || 'Standard') : color,
      batteryHealth: (category === 'pre_owned_phones' || category === 'used_phones') ? 100 : undefined,
      imeiPairs: isPhone && parsedImeis.length > 0 ? parsedImeis : undefined,
      imeiList: isPhone && flattenedImeiList.length > 0 ? flattenedImeiList : undefined,
      dualImei: isPhone ? parsedImeis.some(p => !!p.imei2) : undefined,
      warrantyMonths,
      description,
      lastRestockedAt: new Date().toISOString(),
    };

    // Check if variant matches an existing catalog product
    const isExistingMatch = existingProducts.some(p => 
      p.name.toLowerCase() === rawName.toLowerCase() &&
      (!brand || (p.brand || '').toLowerCase() === brand.toLowerCase()) &&
      (!ram || (p.ram || '').toLowerCase() === ram.toLowerCase()) &&
      (!rom || (p.rom || '').toLowerCase() === rom.toLowerCase()) &&
      (!color || (p.color || '').toLowerCase() === color.toLowerCase())
    );

    const isValid = errors.length === 0;
    if (isValid) {
      totalValid++;
      totalUnits += stock;
      totalValuationCost += (costPrice * stock);
      totalValuationSelling += (sellingPrice * stock);
    } else {
      totalErrors++;
    }

    parsedRows.push({
      rowNumber,
      rawText: line,
      isValid,
      errors,
      warnings,
      product,
      parsedImeis,
      isExistingVariantMatch: isExistingMatch
    });
  });

  return {
    rows: parsedRows,
    totalValid,
    totalErrors,
    totalUnits,
    totalValuationCost,
    totalValuationSelling,
    delimiter
  };
}

/**
 * Built-in Sample CSV Templates for quick copying and reference
 */
export const SAMPLE_CSV_TEMPLATES: CsvTemplatePreset[] = [
  {
    id: 'inventory_export_format',
    name: 'Exported Inventory Stock List Format',
    description: 'Exact format exported from the Inventory screen. Directly re-importable with full SKU, Barcodes, Specs, and IMEIs.',
    csvContent: `"Product Name","Brand","Category","Subcategory","Condition","Cost Price (Ks)","Selling Price (Ks)","Stock (Units)","Min Alert Level","RAM","ROM","Color","Specs / Storage / Color","SKU","Barcode","Serialized IMEIs","Warranty (Months)"
"Redmi 9A","Redmi","Brand new phones","-","Brand New (Sealed)","425000","479000","1","0","4GB","64GB","Black","4GB RAM • 64GB • Black","SKU-435331","111228795337","862675065232361","12"
"Redmi A7pro","Redmi","Brand new phones","-","Brand New (Sealed)","580000","639000","2","0","4GB","64GB","Black","4GB RAM • 64GB • Black","SKU-826254","224338118334","866286085182101; 866704087369401","12"
"Ansty C056 Fast Charger","Ansty","Accessories","Fast Charger","Brand New","3850","6000","40","10","-","-","White","-","SKU-18419","150000293812","-","6"
"Daw Pu ဟင်းချက်အိုး","Daw Pu","Cookware","ဟင်းချက်အိုး","Brand New","620000","770000","2","0","-","-","Silver","-","SKU-99590","901000382910","-","12"`
  },
  {
    id: 'smartphones_imei',
    name: 'Smartphones with Dual IMEIs',
    description: 'Complete phone catalogue with Brand, RAM, ROM, Color, Cost, Selling Price and Serialized Dual IMEIs.',
    csvContent: `Name,Brand,Category,Condition,CostPrice,SellingPrice,Stock,RAM,ROM,Color,IMEIs,Warranty
Apple iPhone 15 Pro,Apple,new_phones,brand_new,3400000,3750000,2,8GB,256GB,Natural Titanium,358765123456789 / 358765123456790; 358765123456791 / 358765123456792,12
Samsung Galaxy S24 Ultra,Samsung,new_phones,brand_new,3800000,4200000,2,12GB,512GB,Titanium Gray,351234098765432 / 351234098765433; 351234098765434 / 351234098765435,12
Xiaomi Redmi Note 13 Pro 5G,Xiaomi,new_phones,brand_new,950000,1050000,3,8GB,256GB,Midnight Black,861234567890123 / 861234567890124; 861234567890125 / 861234567890126; 861234567890127 / 861234567890128,12
Apple iPhone 13 Pro Max (Pre-Owned),Apple,used_phones,used_grade_a,1950000,2250000,1,6GB,128GB,Sierra Blue,359998877665544,1`
  },
  {
    id: 'accessories',
    name: 'Phone Accessories (Chargers, Cables, Cases)',
    description: 'Bulk accessories without IMEIs: original fast chargers, heavy-duty cables, screen protectors, cases, and power banks.',
    csvContent: `Name,Brand,Category,SubCategory,Condition,CostPrice,SellingPrice,Stock,MinAlert,Warranty,Description
Apple 20W USB-C Fast Power Adapter,Apple,accessories,Fast Chargers & Adapters,brand_new,65000,85000,30,5,6,Original Apple 20W USB-C fast power adapter
Anker 737 Power Bank (PowerCore 24K),Anker,accessories,Power Banks,brand_new,260000,320000,12,2,12,140W fast output 24000mAh portable charger with smart digital display
Baseus 100W PD 5A Type-C Cable 1.5m,Baseus,accessories,Cables & Connectors,brand_new,12000,18000,50,10,3,High durability braided fast charging cable
Remax 9D King Kong Tempered Glass (iPhone 15 Pro),Remax,accessories,Screen Protectors,brand_new,6000,12000,60,15,0,Full coverage privacy tempered glass screen protector
UAG Monarch Rugged Case (Samsung S24 Ultra),UAG,accessories,Cases & Covers,brand_new,85000,125000,15,3,12,5-layer heavy duty drop-tested protective case`
  },
  {
    id: 'gadgets',
    name: 'Smart Gadgets (Smartwatches & Audio)',
    description: 'Smart wearable devices, wireless Bluetooth earbuds, portable audio speakers, and lifestyle gadgets.',
    csvContent: `Name,Brand,Category,SubCategory,Condition,CostPrice,SellingPrice,Stock,MinAlert,Warranty,Description
Samsung Galaxy Buds2 Pro,Samsung,gadgets,Wireless Earbuds,brand_new,380000,450000,10,2,6,Active Noise Cancelling 24-bit Hi-Fi sound wireless earbuds
Apple AirPods Pro 2 (USB-C),Apple,gadgets,Wireless Earbuds,brand_new,620000,695000,8,2,12,H2 chip with Adaptive Audio and MagSafe USB-C case
Xiaomi Smart Band 8 Pro,Xiaomi,gadgets,Smartwatches & Bands,brand_new,165000,195000,15,3,6,1.74 inch AMOLED 60Hz display with GNSS and 14-day battery
Haylou Solar Plus RT3 Smartwatch,Haylou,gadgets,Smartwatches & Bands,brand_new,95000,125000,12,3,3,1.43 inch AMOLED Bluetooth phone call smartwatch
JBL Flip 6 Portable Bluetooth Speaker,JBL,gadgets,Bluetooth Speakers,brand_new,290000,350000,6,2,12,2-way speaker system IP67 waterproof and dustproof`
  },
  {
    id: 'simple_quick',
    name: 'Simple Fast Inventory (Minimal Columns)',
    description: 'Quickest copy-paste format: Name, Brand, SellingPrice, CostPrice, Stock, Color.',
    csvContent: `Name,Brand,SellingPrice,CostPrice,Stock,Color
Apple 20W USB-C Power Adapter,Apple,85000,65000,30,White
Samsung Galaxy Buds2 Pro,Samsung,450000,380000,10,Graphite
Remax RPP-296 20000mAh Power Bank,Remax,45000,32000,20,Black
Baseus 100W PD 5A Type-C Cable,Baseus,18000,12000,40,Black
Apple iPhone 15 Pro 256GB Natural Titanium,Apple,3750000,3400000,2,Natural Titanium`
  }
];
